<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="KETAN-PC" ignored="4" name="Default test" tests="1" failures="1" timestamp="10 Jan 2018 16:15:08 GMT" time="38.48" errors="0">
  <testcase name="blankEmailIDLogin" time="10.967" classname="pageFactoryTestCases.LoginPageTestCases">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at core.Action.getControlDescription(Action.java:22)
	at core.Action.isDisplayed(Action.java:220)
	at core.Assertion.assertDisplyed(Assertion.java:55)
	at pageFactoryTestCases.LoginPageTestCases.blankEmailIDLogin(LoginPageTestCases.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- blankEmailIDLogin -->
  <testcase name="getSessionID" time="0.0" classname="pageFactoryTestCases.LoginPageTestCases">
    <ignored/>
  </testcase> <!-- getSessionID -->
  <testcase name="invalidLoginCredentials" time="0.0" classname="pageFactoryTestCases.LoginPageTestCases">
    <ignored/>
  </testcase> <!-- invalidLoginCredentials -->
  <testcase name="validLogin" time="0.0" classname="pageFactoryTestCases.LoginPageTestCases">
    <ignored/>
  </testcase> <!-- validLogin -->
  <testcase name="blankPasswordLogin" time="0.0" classname="pageFactoryTestCases.LoginPageTestCases">
    <ignored/>
  </testcase> <!-- blankPasswordLogin -->
</testsuite> <!-- Default test -->
